### ISSUE TITLE
notarize_action.rb assumes Info.plist is XML

### ISSUE THREAD

**Issue by macblazer** [zeplin/fastlane-plugin-notarize#1]
For apps that compile the Info.plist to a binary format, the run function in notarize_action.rb is not able to parse the file and crashes fastlane.  This is the relevant line that assumes the Info.plist is in XML format.

https://github.com/zeplin/fastlane-plugin-notarize/blob/4f7b75cf4857ab4dc68414b59fd7a82e51bb8089/lib/fastlane/plugin/notarize/actions/notarize_action.rb#L21

Here is the relevant part of the stack trace from the crash:

```
4: from {USER_HOME}/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
3: from USER_HOME/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-plugin-notarize-0.1.0/lib/fastlane/plugin/notarize/actions/notarize_action.rb:21:in `run'
2: from USER_HOME/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/plist-3.5.0/lib/plist/parser.rb:30:in `parse_xml'
1: from USER_HOME/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/plist-3.5.0/lib/plist/parser.rb:90:in `parse'
USER_HOME/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/plist-3.5.0/lib/plist/parser.rb:90:in `scan': [!] invalid byte sequence in UTF-8 (ArgumentError)
```

**Comment by berkcebi** [comment]
Hey @macblazer, thanks for reporting this—will check if there's an alternative helper within fastlane to read Info.plist files in binary format.

Until then, if you pass the bundle identifier to the action, that should do the trick I believe:
```ruby
notarize(
    package: app_path
    bundle_id: bundle_id
)
```
